module:
  id: company
  name: Company
  description: Core company management module
  icon: Building2
  color: module-core
configurables:
  default_currency:
    label: Default Currency
    type: select
    options:
      - USD
      - EUR
      - GBP
    default: USD
  default_timezone:
    label: Default Timezone
    type: text
    default: UTC
  allow_multi_branch:
    label: Allow multiple branches
    type: boolean
    default: false
screens: {}
# No menu - this is a system/infrastructure module that shouldn't appear in sidebar
menu: []
